FROM python:3
RUN git clone https://github.com/FranciscoLopezGarcia/Listas-Diccionario-FranciscoLopezGarcia.git
WORKDIR /Listas-Diccionario-FranciscoLopezGarcia
RUN pip install -r requirements.txt
CMD ["python3",  "-m", "unittest"]
